In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

## fetch 5
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [3]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [5]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

- Handling Missinf Values

In [6]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [7]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [8]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [9]:
df_filled = df.fillna(0)

In [10]:
df_filled

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [11]:
# ## filling missing values with their Mean of the column
# mean = df['Sales'].mean()
# df['Sales'].fillna(mean)
# df

    #-- byme

In [12]:
### filling missing values with their Mean of the column

df['sales_fillna'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  sales_fillna
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [13]:
# df['Sales'].fillna(df['Sales'].mean())
# df

In [14]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
sales_fillna    float64
dtype: object

In [15]:
## Renaming the Column Name

df = df.rename(columns={'Date':'Sale_Date'}) 
df.head()

    Sale_Date Category  Value   Product  Sales Region  sales_fillna
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [16]:
df.rename(columns={'Value':'Sale_Value'})

     Sale_Date Category  Sale_Value   Product  Sales Region  sales_fillna
0   2023-01-01        A        28.0  Product1  754.0   East    754.000000
1   2023-01-02        B        39.0  Product3  110.0  North    110.000000
2   2023-01-03        C        32.0  Product2  398.0   East    398.000000
3   2023-01-04        B         8.0  Product1  522.0   East    522.000000
4   2023-01-05        B        26.0  Product3  869.0  North    869.000000
5   2023-01-06        B        54.0  Product3  192.0   West    192.000000
6   2023-01-07        A        16.0  Product1  936.0   East    936.000000
7   2023-01-08        C        89.0  Product1  488.0   West    488.000000
8   2023-01-09        C        37.0  Product3  772.0   West    772.000000
9   2023-01-10        A        22.0  Product2  834.0   West    834.000000
10  2023-01-11        B         7.0  Product1  842.0  North    842.000000
11  2023-01-12        B        60.0  Product2    NaN   West    557.130435
12  2023-01-13        A        70.0  Product3  628.0  South    628.000000
13  2023-01-14        A        69.0  Product1  423.0   East    423.000000
14  2023-01-15        A        47.0  Product2  893.0   West    893.000000
15  2023-01-16        C         NaN  Product1  895.0  North    895.000000
16  2023-01-17        C        93.0  Product2  511.0  South    511.000000
17  2023-01-18        C         NaN  Product1  108.0   West    108.000000
18  2023-01-19        A        31.0  Product2  578.0   West    578.000000
19  2023-01-20        A        59.0  Product1  736.0   East    736.000000
20  2023-01-21        C        82.0  Product3  606.0  South    606.000000
21  2023-01-22        C        37.0  Product2  992.0  South    992.000000
22  2023-01-23        B        62.0  Product3  942.0  North    942.000000
23  2023-01-24        C        92.0  Product2  342.0   West    342.000000
24  2023-01-25        A        24.0  Product2  458.0   East    458.000000
25  2023-01-26        C        95.0  Product1  584.0   West    584.000000
26  2023-01-27        C        71.0  Product2  619.0  North    619.000000
27  2023-01-28        C        56.0  Product2  224.0  North    224.000000
28  2023-01-29        B         NaN  Product3  617.0  North    617.000000
29  2023-01-30        C        51.0  Product2  737.0  South    737.000000
30  2023-01-31        B        50.0  Product3  735.0   West    735.000000
31  2023-02-01        A        17.0  Product2  189.0   West    189.000000
32  2023-02-02        B        63.0  Product3  338.0  South    338.000000
33  2023-02-03        C        27.0  Product3    NaN   East    557.130435
34  2023-02-04        C        70.0  Product3  669.0   West    669.000000
35  2023-02-05        B        60.0  Product2    NaN   West    557.130435
36  2023-02-06        C        36.0  Product3  177.0   East    177.000000
37  2023-02-07        C         2.0  Product1    NaN  North    557.130435
38  2023-02-08        C        94.0  Product1  408.0  South    408.000000
39  2023-02-09        A        62.0  Product1  155.0   West    155.000000
40  2023-02-10        B        15.0  Product1  578.0   East    578.000000
41  2023-02-11        C        97.0  Product1  256.0   East    256.000000
42  2023-02-12        A        93.0  Product3  164.0   West    164.000000
43  2023-02-13        A        43.0  Product3  949.0   East    949.000000
44  2023-02-14        A        96.0  Product3  830.0   East    830.000000
45  2023-02-15        B        99.0  Product2  599.0   West    599.000000
46  2023-02-16        B         6.0  Product1  938.0  South    938.000000
47  2023-02-17        B        69.0  Product3  143.0   West    143.000000
48  2023-02-18        C        65.0  Product3  182.0  North    182.000000
49  2023-02-19        C        11.0  Product3  708.0  North    708.000000

In [17]:
## Change dataType
df['new_val'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

    Sale_Date Category  Value   Product  Sales Region  sales_fillna  new_val
0  2023-01-01        A   28.0  Product1  754.0   East         754.0       28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0       39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0       32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0        8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0       26

In [18]:
df['double_val'] = df['new_val'].apply(lambda x:x*2)
df.head()

,Sale_Date,Category,Value,Product,Sales,Region,sales_fillna,new_val,double_val
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52

#### Grouped:
- which ,eans based on the particular non-numeric value, we will going to analyse the numerical column in a particular DataSet.

In [19]:
## We will find the mean of value based on the product column which has 3 Products

grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [20]:
grouped_sum = df.groupby('Category')['Product'].sum()
print(grouped_sum)

Category
A    Product1Product1Product2Product3Product1Produc...
B    Product3Product1Product3Product3Product1Produc...
C    Product2Product1Product3Product1Product2Produc...
Name: Product, dtype: object

In [21]:
multi_columns = df.groupby(['Product','Region'])['Sales'].sum()
print(multi_columns)

Product   Region
Product1  East      4205.0
          North     1737.0
          South     1346.0
          West      1335.0
Product2  East       856.0
          North      843.0
          South     2240.0
          West      3435.0
Product3  East      1956.0
          North     3428.0
          South     1572.0
          West      2675.0
Name: Sales, dtype: float64

In [22]:
## Aggregate Functions

grouped_age = df.groupby('Product')['Sales'].agg(['sum','count','mean'])
print(grouped_age)

             sum  count        mean
Product
Product1  8623.0     15  574.866667
Product2  7374.0     13  567.230769
Product3  9631.0     18  535.055556

In [23]:
grouped = df.groupby(['Product','Region'])['Value'].agg(['sum','count','mean'])
print(grouped)

                   sum  count       mean
Product  Region
Product1 East    292.0      7  41.714286
         North     9.0      2   4.500000
         South   100.0      2  50.000000
         West    246.0      3  82.000000
Product2 East     56.0      2  28.000000
         North   127.0      2  63.500000
         South   181.0      3  60.333333
         West    428.0      8  53.500000
Product3 East    202.0      4  50.500000
         North   203.0      5  40.600000
         South   215.0      3  71.666667
         West    373.0      6  62.166667

In [24]:
## Merging and Joining DataFrames

## create Sample DataFrames

df1 = pd.DataFrame({'key':['A','B','C'],'VALUES1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'VALUES2':[4,5,6]})

In [25]:
df1

  key  VALUES1
0   A        1
1   B        2
2   C        3

In [26]:
df2

  key  VALUES2
0   A        4
1   B        5
2   D        6

In [27]:
## Merge DataFrame on the ketColumn

pd.merge(df1,df2,on='key',how='inner')

  key  VALUES1  VALUES2
0   A        1        4
1   B        2        5

In [28]:
pd.merge(df1,df2,on='key',how='outer')

  key  VALUES1  VALUES2
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [29]:
pd.merge(df1,df2,on='key',how="left")

  key  VALUES1  VALUES2
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [30]:
pd.merge(df1,df2,on='key',how='right')

  key  VALUES1  VALUES2
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6

In [31]:
df1 = pd.read_csv("sales1_data.csv")

In [32]:
df1.head(5)

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [33]:
df1.isnull()

     Date  Product  Sales  Region
0   False    False  False   False
1   False    False  False   False
2   False    False  False   False
3   False    False  False   False
4   False    False  False   False
5   False    False   True   False
6   False    False  False   False
7   False    False  False   False
8   False    False  False   False
9   False    False  False   False
10  False    False  False   False
11  False    False   True   False
12  False    False   True   False
13  False    False  False   False
14  False    False  False   False
15  False    False  False   False
16  False    False   True   False
17  False    False   True   False
18  False    False  False   False
19  False    False  False   False
20  False    False   True   False
21  False    False  False   False
22  False    False  False   False
23  False    False  False   False
24  False    False  False   False

In [34]:
df1.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [35]:
df1['salesFilled'] = df['Sales'].fillna(df['Sales'].mean())
df1

          Date   Product  Sales Region  salesFilled
0   2023-01-01  Product3  738.0   West   754.000000
1   2023-01-02  Product2  868.0  North   110.000000
2   2023-01-03  Product2  554.0   West   398.000000
3   2023-01-04  Product1  618.0  South   522.000000
4   2023-01-05  Product3  501.0   East   869.000000
5   2023-01-06  Product1    NaN   West   192.000000
6   2023-01-07  Product3  339.0  South   936.000000
7   2023-01-08  Product3  280.0  South   488.000000
8   2023-01-09  Product2  806.0  North   772.000000
9   2023-01-10  Product2  816.0  South   834.000000
10  2023-01-11  Product3  469.0   West   842.000000
11  2023-01-12  Product3    NaN   East   557.130435
12  2023-01-13  Product3    NaN   East   628.000000
13  2023-01-14  Product3  676.0   East   423.000000
14  2023-01-15  Product1  183.0  South   893.000000
15  2023-01-16  Product1  424.0  South   895.000000
16  2023-01-17  Product1    NaN  South   511.000000
17  2023-01-18  Product1    NaN  South   108.000000
18  2023-01-19  Product2  124.0  North   578.000000
19  2023-01-20  Product3  732.0   West   736.000000
20  2023-01-21  Product2    NaN   West   606.000000
21  2023-01-22  Product3  296.0   West   992.000000
22  2023-01-23  Product2  737.0   West   942.000000
23  2023-01-24  Product3  531.0   East   342.000000
24  2023-01-25  Product2  834.0  North   458.000000

In [36]:
df1['SalesConvert'] = df1['Sales'].fillna(df1['Sales'].mean()).astype(int)
df1

          Date   Product  Sales Region  salesFilled  SalesConvert
0   2023-01-01  Product3  738.0   West   754.000000           738
1   2023-01-02  Product2  868.0  North   110.000000           868
2   2023-01-03  Product2  554.0   West   398.000000           554
3   2023-01-04  Product1  618.0  South   522.000000           618
4   2023-01-05  Product3  501.0   East   869.000000           501
5   2023-01-06  Product1    NaN   West   192.000000           554
6   2023-01-07  Product3  339.0  South   936.000000           339
7   2023-01-08  Product3  280.0  South   488.000000           280
8   2023-01-09  Product2  806.0  North   772.000000           806
9   2023-01-10  Product2  816.0  South   834.000000           816
10  2023-01-11  Product3  469.0   West   842.000000           469
11  2023-01-12  Product3    NaN   East   557.130435           554
12  2023-01-13  Product3    NaN   East   628.000000           554
13  2023-01-14  Product3  676.0   East   423.000000           676
14  2023-01-15  Product1  183.0  South   893.000000           183
15  2023-01-16  Product1  424.0  South   895.000000           424
16  2023-01-17  Product1    NaN  South   511.000000           554
17  2023-01-18  Product1    NaN  South   108.000000           554
18  2023-01-19  Product2  124.0  North   578.000000           124
19  2023-01-20  Product3  732.0   West   736.000000           732
20  2023-01-21  Product2    NaN   West   606.000000           554
21  2023-01-22  Product3  296.0   West   992.000000           296
22  2023-01-23  Product2  737.0   West   942.000000           737
23  2023-01-24  Product3  531.0   East   342.000000           531
24  2023-01-25  Product2  834.0  North   458.000000           834

In [37]:
df1.rename(columns={'SalesRegion':'productRegion'},inplace=True)

In [38]:
df1

          Date   Product  Sales Region  salesFilled  SalesConvert
0   2023-01-01  Product3  738.0   West   754.000000           738
1   2023-01-02  Product2  868.0  North   110.000000           868
2   2023-01-03  Product2  554.0   West   398.000000           554
3   2023-01-04  Product1  618.0  South   522.000000           618
4   2023-01-05  Product3  501.0   East   869.000000           501
5   2023-01-06  Product1    NaN   West   192.000000           554
6   2023-01-07  Product3  339.0  South   936.000000           339
7   2023-01-08  Product3  280.0  South   488.000000           280
8   2023-01-09  Product2  806.0  North   772.000000           806
9   2023-01-10  Product2  816.0  South   834.000000           816
10  2023-01-11  Product3  469.0   West   842.000000           469
11  2023-01-12  Product3    NaN   East   557.130435           554
12  2023-01-13  Product3    NaN   East   628.000000           554
13  2023-01-14  Product3  676.0   East   423.000000           676
14  2023-01-15  Product1  183.0  South   893.000000           183
15  2023-01-16  Product1  424.0  South   895.000000           424
16  2023-01-17  Product1    NaN  South   511.000000           554
17  2023-01-18  Product1    NaN  South   108.000000           554
18  2023-01-19  Product2  124.0  North   578.000000           124
19  2023-01-20  Product3  732.0   West   736.000000           732
20  2023-01-21  Product2    NaN   West   606.000000           554
21  2023-01-22  Product3  296.0   West   992.000000           296
22  2023-01-23  Product2  737.0   West   942.000000           737
23  2023-01-24  Product3  531.0   East   342.000000           531
24  2023-01-25  Product2  834.0  North   458.000000           834

In [43]:
grouped1 = df1.groupby('Product')['Sales'].mean()
print(grouped1)

Product
Product1    408.333333
Product2    677.000000
Product3    506.888889
Name: Sales, dtype: float64

In [ ]:
grouped2= df1.groupby(['productRegion','Region'])[['Sales','salesFilled']].agg(['mean','sum'])
print(grouped2)

                           Sales         salesFilled
                            mean     sum        mean          sum
productRegion Region
Product1      South   408.333333  1225.0  585.800000  2929.000000
              West           NaN     0.0  192.000000   192.000000
Product2      North   658.000000  2632.0  479.500000  1918.000000
              South   816.000000   816.0  834.000000   834.000000
              West    645.500000  1291.0  648.666667  1946.000000
Product3      East    569.333333  1708.0  563.826087  2819.130435
              South   309.500000   619.0  712.000000  1424.000000
              West    558.750000  2235.0  831.000000  3324.000000

In [ ]:
df1.head(6)

         Date productRegion  Sales Region  salesFilled  SalesConvert
0  2023-01-01      Product3  738.0   West        754.0           738
1  2023-01-02      Product2  868.0  North        110.0           868
2  2023-01-03      Product2  554.0   West        398.0           554
3  2023-01-04      Product1  618.0  South        522.0           618
4  2023-01-05      Product3  501.0   East        869.0           501
5  2023-01-06      Product1    NaN   West        192.0           554

In [ ]:
df.head(6)

,Sale_Date,Category,Value,Product,Sales,Region,sales_fillna,new_val,double_val
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52
5,2023-01-06,B,54.0,Product3,192.0,West,192.0,54,108

In [40]:
outer = pd.merge(df,df1,on="Region",how="outer")
print(outer)

      Sale_Date Category  Value Product_x  Sales_x Region  sales_fillna  \
0    2023-01-01        A   28.0  Product1    754.0   East         754.0
1    2023-01-01        A   28.0  Product1    754.0   East         754.0
2    2023-01-01        A   28.0  Product1    754.0   East         754.0
3    2023-01-01        A   28.0  Product1    754.0   East         754.0
4    2023-01-01        A   28.0  Product1    754.0   East         754.0
..          ...      ...    ...       ...      ...    ...           ...
312  2023-02-17        B   69.0  Product3    143.0   West         143.0
313  2023-02-17        B   69.0  Product3    143.0   West         143.0
314  2023-02-17        B   69.0  Product3    143.0   West         143.0
315  2023-02-17        B   69.0  Product3    143.0   West         143.0
316  2023-02-17        B   69.0  Product3    143.0   West         143.0

     new_val  double_val        Date Product_y  Sales_y  salesFilled  \
0         28          56  2023-01-05  Product3    501.0   869.000000
1         28          56  2023-01-12  Product3      NaN   557.130435
2         28          56  2023-01-13  Product3      NaN   628.000000
3         28          56  2023-01-14  Product3    676.0   423.000000
4         28          56  2023-01-24  Product3    531.0   342.000000
..       ...         ...         ...       ...      ...          ...
312       69         138  2023-01-11  Product3    469.0   842.000000
313       69         138  2023-01-20  Product3    732.0   736.000000
314       69         138  2023-01-21  Product2      NaN   606.000000
315       69         138  2023-01-22  Product3    296.0   992.000000
316       69         138  2023-01-23  Product2    737.0   942.000000

     SalesConvert
0             501
1             554
2             554
3             676
4             531
..            ...
312           469
313           732
314           554
315           296
316           737

[317 rows x 14 columns]